[package]
name = "nback"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = ["bevy_egui"]

[dependencies]
bevy = { version = "0.18.1" }
bevy_asset_loader = "0.26.0"
bevy_egui = { version = "0.39.1", optional = true, default-features = false, features = [
    "open_url",
    "default_fonts",
    "render",
    "bevy_ui",
] }
bevy_embedded_assets = "0.15.0"
bevy_kira_audio = "0.25.0"
image = "0.25.10"
rand = "0.10.0"

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
