# Enable fast compiles following Bevy's setup guide:
# https://bevy.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional

# NOTE: On MacOS, the default system linker `ld-prime` is faster than LLD.
# No linker override is needed for macOS targets.

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=lld", # Use LLD Linker
    "-Zshare-generics=y",      # (Nightly) Make the current crate share its generic instantiations
    "-Zthreads=0",             # (Nightly) Use improved multithreading with the recommended amount of threads.
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe" # Use LLD Linker
rustflags = [
    "-Zshare-generics=n", # (Nightly)
    "-Zthreads=0",        # (Nightly) Use improved multithreading with the recommended amount of threads.
]
